"""add automation rule config

Revision ID: 20b458b6c3ff
Revises: 40303450d23e
Create Date: 2026-07-09 17:17:05.226615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b458b6c3ff'
down_revision: Union[str, Sequence[str], None] = '40303450d23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "automation_rules",
        sa.Column(
            "config",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )

    op.alter_column(
        "automation_rules",
        "config",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_rules', 'config')
    # ### end Alembic commands ###
