"""create incidents table

Revision ID: 321484be3caf
Revises: 13444be3fc5d
Create Date: 2026-07-04 16:16:43.097439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321484be3caf'
down_revision: Union[str, Sequence[str], None] = '13444be3fc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('incidents', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('incidents', 'ai_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('incidents', 'recommendation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_column('incidents', 'service')
    op.drop_column('incidents', 'status')
    op.drop_column('incidents', 'severity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('incidents', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('incidents', sa.Column('service', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    op.alter_column('incidents', 'recommendation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('incidents', 'ai_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('incidents', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('incidents', 'title')
    # ### end Alembic commands ###
