"""initial schema

Revision ID: 56380a077d2c
Revises: 
Create Date: 2026-07-15 17:57:46.064929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56380a077d2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('analysis_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('automation_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='automationstatus'), nullable=False),
    sa.Column('severity', sa.Enum('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'CUSTOM', 'PROMETHEUS', 'GRAFANA', 'GITHUB', name='incidentsource'), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
